"""add final_report to analysis_requests

Revision ID: 3e6a3580cec5
Revises: 3722e3ddd6d9
Create Date: 2026-08-01 16:57:41.898889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6a3580cec5'
down_revision: Union[str, Sequence[str], None] = '3722e3ddd6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_requests', sa.Column('final_report', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_requests', 'final_report')
    # ### end Alembic commands ###
