"""add not null constraints and server defaults to escalated, node_history and status

Revision ID: ad5f1aeffb07
Revises: 0de844826ad4
Create Date: 2026-07-16 21:24:35.463364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad5f1aeffb07'
down_revision: Union[str, Sequence[str], None] = '0de844826ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approvals', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'"),
               nullable=False)
    op.alter_column('tickets', 'escalated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('tickets', 'node_history',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'"),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'node_history',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               nullable=True)
    op.alter_column('tickets', 'escalated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('approvals', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
