"""create analysis_requests and findings tables

Revision ID: fc10589eb440
Revises: 3f2af789409e
Create Date: 2026-07-29 20:27:59.826307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc10589eb440'
down_revision: Union[str, Sequence[str], None] = '3f2af789409e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('pasted_code', sa.Text(), nullable=True),
    sa.Column('review_request', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(source_type = 'github_repo' AND repo_url IS NOT NULL AND pasted_code IS NULL) OR (source_type = 'pasted_code' AND pasted_code IS NOT NULL AND repo_url IS NULL)", name='ck_analysis_requests_exactly_one_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_request_id', sa.Integer(), nullable=False),
    sa.Column('specialist', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_request_id'], ['analysis_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_analysis_request_id'), 'findings', ['analysis_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_analysis_request_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_table('analysis_requests')
    # ### end Alembic commands ###
